<?php
declare(strict_types=1);
session_start(); require __DIR__.'/db.php';
function h(?string $v):string{return htmlspecialchars($v??'',ENT_QUOTES,'UTF-8');}
$categories=['Alimentação','Locomoção','Hospedagem','Passeios e ingressos','Lembrancinhas','Compras','Seguro e saúde','Taxas','Outros'];
$cities=$pdo->query('SELECT id,name FROM cities ORDER BY sort_order,id')->fetchAll();
$cityId=filter_input(INPUT_GET,'cidade',FILTER_VALIDATE_INT)?:filter_input(INPUT_POST,'city_id',FILTER_VALIDATE_INT)?:($cities[0]['id']??0); $message='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!hash_equals($_SESSION['csrf']??'',$_POST['csrf']??'')){http_response_code(403);exit('Sessão expirada.');}
 $id=filter_input(INPUT_POST,'id',FILTER_VALIDATE_INT); $action=$_POST['action']??'save';
 if($action==='delete'&&$id){$pdo->prepare('DELETE FROM expenses WHERE id=?')->execute([$id]);$message='Gasto excluído.';}
 else{$amount=str_replace(',','.',trim((string)($_POST['amount_usd']??'0')));$category=in_array($_POST['category']??'',$categories,true)?$_POST['category']:'Outros';$status=($_POST['status']??'paid')==='planned'?'planned':'paid';$data=[':city_id'=>$cityId,':name'=>trim((string)$_POST['name']),':category'=>$category,':amount_usd'=>(float)$amount,':expense_date'=>$_POST['expense_date']?:date('Y-m-d'),':status'=>$status,':notes'=>trim((string)($_POST['notes']??''))];if($id){$data[':id']=$id;$pdo->prepare('UPDATE expenses SET city_id=:city_id,name=:name,category=:category,amount_usd=:amount_usd,expense_date=:expense_date,status=:status,notes=:notes WHERE id=:id')->execute($data);}else{$pdo->prepare('INSERT INTO expenses(city_id,name,category,amount_usd,expense_date,status,notes) VALUES(:city_id,:name,:category,:amount_usd,:expense_date,:status,:notes)')->execute($data);}$message='Gasto salvo.';}
}
$_SESSION['csrf']=bin2hex(random_bytes(24));$stmt=$pdo->prepare('SELECT * FROM expenses WHERE city_id=? ORDER BY expense_date DESC,id DESC');$stmt->execute([$cityId]);$items=$stmt->fetchAll();$cityTotal=0.0;foreach($items as $row)if($row['status']==='paid')$cityTotal+=(float)$row['amount_usd'];$tripTotal=(float)$pdo->query("SELECT COALESCE(SUM(amount_usd),0) FROM expenses WHERE status='paid'")->fetchColumn();
$editId=filter_input(INPUT_GET,'editar',FILTER_VALIDATE_INT);$edit=null;foreach($items as $item)if((int)$item['id']===(int)$editId)$edit=$item;$edit??=['id'=>'','city_id'=>$cityId,'name'=>'','category'=>'Alimentação','amount_usd'=>'','expense_date'=>date('Y-m-d'),'status'=>'paid','notes'=>''];
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Gastos</title><link rel="stylesheet" href="assets/style.css"><link rel="stylesheet" href="assets/features.css"></head><body>
<header class="topbar compact"><div><p class="eyebrow">PLANEJADOR DE VIAGEM</p><h1>Registro de gastos</h1></div><div class="mini-total"><small>Total pago</small><strong>$ <?=number_format($tripTotal,2,'.',',')?></strong></div></header>
<main class="manage-layout"><section class="form-card"><?php if($message):?><div class="success"><?=h($message)?></div><?php endif;?><div class="manage-top"><form class="city-filter" method="get"><label>Cidade<select name="cidade" onchange="this.form.submit()"><?php foreach($cities as $city):?><option value="<?=$city['id']?>" <?=$city['id']==$cityId?'selected':''?>><?=h($city['name'])?></option><?php endforeach;?></select></label></form><a href="index.php?cidade=<?=$cityId?>">← Voltar</a></div>
<h2><?= $edit['id']?'Editar gasto':'Novo gasto'?></h2><form method="post"><input type="hidden" name="csrf" value="<?=h($_SESSION['csrf'])?>"><input type="hidden" name="id" value="<?=h((string)$edit['id'])?>"><input type="hidden" name="city_id" value="<?=$cityId?>"><div class="form-grid"><label class="wide">Nome<input required name="name" value="<?=h($edit['name'])?>"></label><label>Tipo<select name="category"><?php foreach($categories as $category):?><option <?=$edit['category']===$category?'selected':''?>><?=h($category)?></option><?php endforeach;?></select></label><label>Valor em dólar<input required inputmode="decimal" name="amount_usd" placeholder="0.00" value="<?=h((string)$edit['amount_usd'])?>"></label><label>Data<input required type="date" name="expense_date" value="<?=h($edit['expense_date'])?>"></label><label>Situação<select name="status"><option value="paid" <?=$edit['status']==='paid'?'selected':''?>>Pago</option><option value="planned" <?=$edit['status']==='planned'?'selected':''?>>Previsto</option></select></label><label class="wide">Observações<input name="notes" value="<?=h($edit['notes'])?>"></label></div><button class="save">Salvar gasto</button></form></section>
<aside class="records-panel"><h2>$ <?=number_format((float)$cityTotal,2,'.',',')?> <small>nesta cidade</small></h2><?php foreach($items as $item):?><article><div><strong><?=h($item['name'])?></strong><p><?=h($item['category'])?> · <?=date('d/m/Y',strtotime($item['expense_date']))?></p></div><div class="record-value">$ <?=number_format((float)$item['amount_usd'],2,'.',',')?></div><div class="record-actions"><a href="?cidade=<?=$cityId?>&editar=<?=$item['id']?>">Editar</a><form method="post" onsubmit="return confirm('Excluir este gasto?')"><input type="hidden" name="csrf" value="<?=h($_SESSION['csrf'])?>"><input type="hidden" name="city_id" value="<?=$cityId?>"><input type="hidden" name="id" value="<?=$item['id']?>"><input type="hidden" name="action" value="delete"><button>Excluir</button></form></div></article><?php endforeach;?><?php if(!$items):?><p>Nenhum gasto nesta cidade.</p><?php endif;?></aside></main></body></html>
